networks:
  asynqhub-network:
    driver: bridge
    name: asynqhub-network

services:
  redis:
    image: redis:alpine
    ports:
      - "16379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./.volumes/redis:/data
    networks:
      - asynqhub-network

  postgres:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: asynqhub
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d asynqhub"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - ./.volumes/postgres:/var/lib/postgresql/data
    networks:
      - asynqhub-network
      
  asynqmon:
    image: hibiken/asynqmon:latest
    restart: always
    environment:
      REDIS_ADDR: redis:6379
    ports:
      - "18080:8080"
    depends_on:
      - redis
    networks:
      - asynqhub-network
