apiVersion: v1
kind: Secret
metadata:
  name: asynqhub-backend-secret
  labels:
    app: asynqhub-backend
type: Opaque
stringData:
  REDIS_ADDR: "redis://asynqhub-redis:6379/0"
  POSTGRES_DSN: "postgresql://postgres:postgres@asynqhub-postgres:5432/asynqhub?sslmode=disable"
