apiVersion: v1
kind: Secret
metadata:
  name: taskpm-backend-secret
  labels:
    app: taskpm-backend
type: Opaque
stringData:
  REDIS_ADDR: "redis://taskpm-redis:6379/0"
  POSTGRES_DSN: "postgresql://postgres:postgres@taskpm-postgres:5432/taskpm?sslmode=disable"
