apiVersion: v1
kind: Service
metadata:
  name: asynqhub-backend
  labels:
    app: asynqhub-backend
    component: backend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 28080
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 29090
    targetPort: grpc
    protocol: TCP
  selector:
    app: asynqhub-backend
    component: backend
