apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asynqhub.backend.fullname" . }}-secret
  labels:
    {{- include "asynqhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  postgres-password: "postgres"
