apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "asynqhub.worker.fullname" . }}
  labels:
    {{- include "asynqhub.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "asynqhub.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "asynqhub.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      serviceAccountName: {{ include "asynqhub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: worker
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        env:
        - name: WORKER_NAME
          value: {{ .Values.worker.config.workerName | quote }}
        - name: BASE_URL
          value: {{ .Values.worker.config.baseURL | quote }}
        - name: REDIS_ADDR
          value: "redis://{{ .Values.worker.redis.host }}:{{ .Values.worker.redis.port }}/{{ .Values.worker.redis.database }}"
        resources:
          {{- toYaml .Values.worker.resources | nindent 12 }}
      terminationGracePeriodSeconds: 60
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
