apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskpm-prod

bases:
- ../../base

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: taskpm-backend
  spec:
    replicas: 3
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: taskpm-worker
  spec:
    replicas: 3

commonLabels:
  environment: prod
