apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskpm.backend.fullname" . }}-secret
  labels:
    {{- include "taskpm.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  postgres-password: "postgres"
