apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskpm.backend.fullname" . }}
  labels:
    {{- include "taskpm.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - name: http
    port: {{ .Values.backend.service.httpPort }}
    targetPort: http
    protocol: TCP
  - name: grpc
    port: {{ .Values.backend.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
  selector:
    {{- include "taskpm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
